# Read the Docs builds and publish our documentation
#
# Config reference: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  builder: dirhtml

python:
  version: 3
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
